## Modifying to run only for $(ROOT)/test/test_demo_script.py
## For demonstration purposes. Base commands to remain the same
## TODO: Remove the filename for running a more comprehensive scan

name: Python - SonarCloud Demo
on:
  push:
    branches:
      - main
      - dev
      - covbase
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  build:

    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies (pytest, pylint, bandit, coverage, pytest-cov)
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint bandit

      - name: Run pytest
        run: |
          pytest -v --junit-xml=pytest_report.xml || true
          echo "--- pytest test cases finished ----"

      - name: Run Bandit SAST
        run: |
          bandit -r test/ -f json -o bandit_report.json || true

      - name: Run pylint
        run: |
          pylint --recursive y --output-format=json ./test > pylint_report.json || true

#       - name: Display Results
#         run: |
#           ## Line separator for pytest results
#           echo "-------------- BEGIN: pytest Test Results ------------------"
#           cat pytest_report.xml
#           echo "-------------- END: pytest Test Results ------------------"
#           echo "-------------- BEGIN: bandit Test Results ------------------"
#           cat bandit_report.json
#           echo "-------------- END: bandit Test Results ------------------"
#           echo "-------------- BEGIN: pylint Test Results ------------------"
#           cat pylint_report.json
#           echo "-------------- END: pylint Test Results ------------------"

      - name: Show Report
        uses: actions/upload-artifact@v2
        with:
          name: code-reports
            path: pytest_report.xml, bandit_report.json, pylint_report.json

#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env: 
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.pullrequest.provider=gitHub
#             -Dsonar.organization=sssamidc
#             -Dsonar.pullrequest.github.repository=sonarcloud_test_py
#             -Dsonar.projectKey=sssamidc_sonarcloud_test_py
#             -Dsonar.pullrequest.key=${{ github.pull_request.number }}
#             -Dsonar.pullrequest.base=${{ github.base_ref }}
#             -Dsonar.pullrequest.branch=${{ github.head_ref }}
#             -X
