name: Python - SonarCloud Demo
on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  SonarCloudPython:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sssamidc
            -Dsonar.projectKey=sssamidc_sonarcloud_test_py
            -Dsonar.pullrequest.base=main
            -Dsonar.pullrequest.key=${{ github.pull_request.number }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
