name: Python - SonarCloud Demo
on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  SonarCloudPython:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage bandit
      - name: Run Bandit SAST
        run: bandit -r ./src/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.provider=gitHub
            -Dsonar.organization=sssamidc
            -Dsonar.pullrequest.github.repository=sonarcloud_test_py
            -Dsonar.projectKey=sssamidc_sonarcloud_test_py
            -Dsonar.pullrequest.key=${{ github.pull_request.number }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -X
