## Modifying to run only for test_demo_script.py
## For demonstration purposes. Base commands to remain the same
## TODO: Remove the filename for running a more comprehensive scan

name: Python - SonarCloud Demo
on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  SonarCloudPython:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint bandit coverage

      - name: Run pytest
        run: |
          coverage run --source=src pytest
          coverage xml -o coverage.xml 

      - name: Run Bandit SAST
        run: |
          bandit -r ./

      - name: Run pylint
        run: |
          pylint --recursive y ./

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.provider=gitHub
            -Dsonar.organization=sssamidc
            -Dsonar.pullrequest.github.repository=sonarcloud_test_py
            -Dsonar.projectKey=sssamidc_sonarcloud_test_py
            -Dsonar.pullrequest.key=${{ github.pull_request.number }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -X


## From Codeium
name: Python Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        coverage run -m pytest
        coverage xml -o coverage.xml

    - name: Run bandit
      run: |
        bandit -r your_python_code_directory -f xml -o bandit_report.xml

    - name: Run pylint
      run: |
        pylint your_python_code_directory --output-format=pylint_json > pylint_report.json

    - name: Publish coverage results
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
